const path = require('path');

const appRoot = path.resolve(__dirname, '../..');

module.exports = {
  apps: [
    {
      name: 'evolution-api',
      cwd: appRoot,
      script: 'dist/main.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 30000,
      listen_timeout: 60000,
      time: true,
      merge_logs: true,
      env_production: {
        NODE_ENV: 'PROD',
        SERVER_NAME: 'simpliweb-evolution',
        SERVER_TYPE: 'http',
        SERVER_HOST: '127.0.0.1',
        SERVER_PORT: '7480',
        SERVER_URL: 'http://127.0.0.1:7480',
        SHUTDOWN_TIMEOUT_MS: '25000',
        SERVER_DISABLE_DOCS: 'true',
        SERVER_DISABLE_MANAGER: 'true',
        CORS_ORIGIN: 'https://app.simpliweb.com.br',
        CORS_CREDENTIALS: 'false',
        DATABASE_PROVIDER: 'postgresql',
        DATABASE_CONNECTION_CLIENT_NAME: 'simpliweb-evolution',
        DATABASE_SAVE_DATA_INSTANCE: 'true',
        DATABASE_SAVE_DATA_NEW_MESSAGE: 'false',
        DATABASE_SAVE_MESSAGE_UPDATE: 'false',
        DATABASE_SAVE_DATA_CONTACTS: 'false',
        DATABASE_SAVE_DATA_CHATS: 'false',
        DATABASE_SAVE_DATA_HISTORIC: 'false',
        DATABASE_SAVE_DATA_LABELS: 'false',
        DATABASE_SAVE_IS_ON_WHATSAPP: 'false',
        DATABASE_DELETE_MESSAGE: 'false',
        CONFIG_SESSION_PHONE_MESSAGES_INGEST_ENABLED: 'false',
        CACHE_REDIS_ENABLED: 'true',
        CACHE_REDIS_PREFIX_KEY: 'evolution-cache',
        CACHE_REDIS_TTL: '604800',
        CACHE_REDIS_SAVE_INSTANCES: 'true',
        CACHE_LOCAL_ENABLED: 'true',
        CACHE_LOCAL_TTL: '86400',
        AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: 'false',
        LOG_LEVEL: 'ERROR,WARN,INFO',
        LOG_COLOR: 'false',
        LOG_BAILEYS: 'error',
        DEL_INSTANCE: 'false',
        DEL_TEMP_INSTANCES: 'true',
        LANGUAGE: 'pt-BR',
        WEBSOCKET_ENABLED: 'false',
        PROMETHEUS_METRICS: 'false',
        TELEMETRY_ENABLED: 'false',
      },
    },
  ],
};